/**
 * The feature registry — every user-facing action in Genga Studio that is NOT a tool.
 *
 * A tool executes. A feature *teaches*: it navigates to where the control lives,
 * pulses it, and hands back the sentence a human would follow. Together with the
 * tool catalogue this is the whole application, one entry per thing you can do,
 * which is what makes the ⌘K palette and `show_me` complete rather than a curated
 * highlight reel. Registry entries here are palette-only (`surfaces.agent:false`),
 * so they do not spend the agent's tool budget — `list_features` and `show_me`
 * still reach them.
 *
 * Owned by workstream I. See docs/WEBMCP-PLAN.md §4 "Feature registry".
 */
import type { ActionContext, ActionDef, ToolResult, Where } from "./contract";
import { ANCHORS, err, genFieldAnchor, genSubAnchor, ok, shotTabAnchor } from "./contract";
import { ROUTES } from "../routes";

const FILM = ROUTES.film;
const SHOT = ROUTES.shot;
const TIMELINE = ROUTES.timeline;
const CHAT = ROUTES.chat;
const JOBS = ROUTES.jobs;
const SETTINGS = ROUTES.settings;
const PROJECTS = ROUTES.projects;

/** The shot the human is looking at, so `:sid` routes can resolve themselves. */
function currentSid(ctx: ActionContext): string | null {
  try {
    const cur = ctx.page.current();
    if (cur?.kind === "shot") return cur.sid;
    if (cur?.kind === "film") return cur.getState().selected ?? null;
  } catch { /* no handles yet */ }
  return null;
}

/**
 * Navigate to where a feature lives and pulse its control. This is the one
 * execution path every palette-only entry shares: `trail.step` does the pulse,
 * so the human sees the same ring the tools draw.
 */
export async function walkTo(ctx: ActionContext, def: ActionDef, where: Where): Promise<ToolResult> {
  let route = where.route;
  if (route.includes(":pid")) {
    if (!ctx.project) {
      return err("no_project", { hint: "Open a project first, then ask again." });
    }
    route = route.replace(":pid", ctx.project);
  }
  if (route.includes(":sid")) {
    const sid = currentSid(ctx);
    if (!sid) {
      return err("needs_shot", {
        where: where.label,
        hint: `"${def.title}" lives inside the Shot Editor — open a shot first (open_shot), then ask again.`,
      });
    }
    route = route.replace(":sid", sid);
  }
  const params = new URLSearchParams();
  for (const [k, v] of Object.entries(where.query || {})) if (v) params.set(k, v);
  const url = `${route}${params.toString() ? `?${params}` : ""}`;

  try { await ctx.nav(url); }
  catch (e) {
    return err("nav_failed", { hint: `Could not open ${url}: ${(e as Error)?.message ?? ""}`.trim() });
  }
  await ctx.trail.step({
    tool: def.name, title: `Here: ${where.label}`,
    anchor: where.anchor, detail: def.howTo,
  });
  return ok(def.howTo || `${def.title} — ${where.label}`, {
    feature: def.name, title: def.title, where: where.label, route: url,
    how_to: def.howTo,
  });
}

interface Spec {
  name: string;
  title: string;
  /** One sentence, ≤200 chars: what this control does. */
  description: string;
  group: string;
  route: string;
  query?: Record<string, string>;
  anchor?: string;
  label: string;
  keywords: string[];
  howTo: string;
}

/** Palette-only ActionDef from a compact row. */
function feature(spec: Spec): ActionDef {
  const where: Where = {
    route: spec.route, query: spec.query, anchor: spec.anchor, label: spec.label,
  };
  const def: ActionDef = {
    name: spec.name,
    title: spec.title,
    description: spec.description,
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    annotations: { readOnlyHint: true },
    where,
    keywords: spec.keywords,
    howTo: spec.howTo,
    group: spec.group,
    surfaces: { agent: false, palette: true },
    summarize: () => `Show me ${spec.title}`,
    execute: (_a, ctx) => walkTo(ctx, def, where),
  };
  return def;
}

const SPECS: Spec[] = [
  // ------------------------------------------------------------------ App shell
  { name: "go_to_projects", title: "Projects list", group: "App shell",
    description: "Every project on this server, with its shot count and pause state.",
    route: PROJECTS, anchor: ANCHORS.navProjects, label: "Sidebar → Projects",
    keywords: ["projects", "home", "switch project", "list"],
    howTo: "Click Projects at the top of the sidebar." },
  { name: "go_to_film_editor", title: "Film Editor", group: "App shell",
    description: "The whole film as a strip of shots — where you arrange, pick what plays and cut.",
    route: FILM, anchor: ANCHORS.navFilm, label: "Sidebar → Film Editor",
    keywords: ["film", "editor", "strip", "overview", "shots"],
    howTo: "Click Film Editor in the sidebar (it appears once a project is open)." },
  { name: "go_to_timeline", title: "Timeline", group: "App shell",
    description: "The film as real clips with source in/out points, plus the live preview player.",
    route: TIMELINE, anchor: ANCHORS.navTimeline, label: "Sidebar → Timeline",
    keywords: ["timeline", "clips", "preview", "tracks"],
    howTo: "Click Timeline in the sidebar." },
  { name: "go_to_chat", title: "Director chat", group: "App shell",
    description: "The line to the machines: plain-language direction that compiles into edit plans.",
    route: CHAT, anchor: ANCHORS.navChat, label: "Sidebar → Director chat",
    keywords: ["chat", "director", "talk", "llm", "assistant"],
    howTo: "Click Director chat in the sidebar." },
  { name: "go_to_jobs", title: "Jobs", group: "App shell",
    description: "Every queued, running and finished job with its live log.",
    route: JOBS, anchor: ANCHORS.navJobs, label: "Sidebar → Jobs",
    keywords: ["jobs", "queue", "running", "log", "progress"],
    howTo: "Click Jobs in the sidebar." },
  { name: "go_to_settings", title: "Settings", group: "App shell",
    description: "Generation backends, per-lane defaults and the API token for hosted instances.",
    route: SETTINGS, anchor: ANCHORS.navSettings, label: "Sidebar → Settings",
    keywords: ["settings", "backends", "config", "keys"],
    howTo: "Click Settings at the bottom of the sidebar's links." },
  { name: "pause_generation", title: "Pause all generation", group: "App shell",
    description: "Stop every GPU and API pool from starting new work; running jobs finish. The CPU pool keeps going.",
    route: FILM, anchor: ANCHORS.pause, label: "Topbar → pause",
    keywords: ["pause", "stop", "halt", "resume", "sentinel"],
    howTo: "Press ⏸ pause in the topbar; press ▶ resume to let the pools start work again." },
  { name: "open_command_palette", title: "Command palette", group: "App shell",
    description: "Fuzzy-search every feature in Genga Studio by name, and jump straight to its control.",
    route: FILM, anchor: ANCHORS.paletteInput, label: "⌘K palette",
    keywords: ["palette", "search", "command", "cmd k", "find feature"],
    howTo: "Press ⌘K (Ctrl+K on Windows) anywhere and type." },
  { name: "agent_trail", title: "Agent trail", group: "App shell",
    description: "The replayable log of what the agent did: each step, its tool and the control it touched.",
    route: FILM, anchor: ANCHORS.agentChip, label: "Topbar → agent chip",
    keywords: ["trail", "agent", "history", "what happened", "webmcp"],
    howTo: "Click the 🤖 chip in the topbar to open the trail; click a step to re-pulse its control." },

  // ------------------------------------------------------------------ Projects
  // "create_project" is a TOOL now (workstream K), so it is not repeated here.
  { name: "import_project", title: "Import a production repo", group: "Projects",
    description: "Index a studio folder (shots.jsonl, renders/, audio/) into a project. Media is copied; it runs as a job.",
    route: PROJECTS, anchor: ANCHORS.projectsImport, label: "Projects → Import",
    keywords: ["import", "repo", "shots.jsonl", "existing", "ingest"],
    howTo: "Fill the repo path and a project slug under \"Import an existing production repo\", then press import." },
  { name: "open_project", title: "Open a project", group: "Projects",
    description: "Open a project's Film Editor from its card.",
    route: PROJECTS, anchor: ANCHORS.projectsCard, label: "Projects → project card",
    keywords: ["open", "project", "card", "switch"],
    howTo: "Click a project card on the Projects page." },

  // ------------------------------------------------------------------ Film Editor
  { name: "toggle_film_view", title: "Toggle the film view", group: "Film Editor",
    description: "Switch the strip between the compact grid and the detailed list of shots.",
    route: FILM, anchor: ANCHORS.filmView, label: "Film Editor → view toggle",
    keywords: ["view", "grid", "list", "compact", "layout"],
    howTo: "Press the view button above the shot strip." },
  { name: "set_cut_scope", title: "Choose what to cut", group: "Film Editor",
    description: "Scope the assembly to the whole film or one act before cutting.",
    route: FILM, anchor: ANCHORS.filmScope, label: "Film Editor → scope",
    keywords: ["scope", "act", "full", "range", "cut"],
    howTo: "Pick a scope in the dropdown next to the Cut button." },
  { name: "set_cut_resolution", title: "Choose the cut resolution", group: "Film Editor",
    description: "Render the animatic at 720p (fast, for watching) or 1080p (for showing).",
    route: FILM, anchor: ANCHORS.filmRes, label: "Film Editor → resolution",
    keywords: ["resolution", "720", "1080", "quality", "render size"],
    howTo: "Pick 720 or 1080 in the resolution dropdown beside the Cut button." },
  { name: "select_shot", title: "Select a shot", group: "Film Editor",
    description: "Click a shot in the strip to load its quick panel: timing, what plays, and the link into the Shot Editor.",
    route: FILM, anchor: ANCHORS.filmShot, label: "Film Editor → shot strip",
    keywords: ["select", "shot", "click", "strip", "choose"],
    howTo: "Click a shot's cell in the strip." },
  { name: "open_shot_editor", title: "Open the Shot Editor", group: "Film Editor",
    description: "Go from the selected shot in the strip into its own room: takes, generate, motion, audio, script.",
    route: FILM, anchor: ANCHORS.quickOpen, label: "Film Editor → open Shot Editor",
    keywords: ["open", "shot editor", "drill in", "room"],
    howTo: "Select a shot, then press \"open Shot Editor →\" in its quick panel." },
  { name: "set_shot_seconds", title: "Shot duration", group: "Film Editor",
    description: "Override how long this shot holds in the cut, in seconds.",
    route: FILM, anchor: ANCHORS.quickSeconds, label: "Film Editor → quick panel → seconds",
    keywords: ["seconds", "duration", "length", "hold", "timing"],
    howTo: "Select a shot and edit the seconds field in the quick panel (it commits when you leave the field)." },
  { name: "set_vo_offset", title: "VO offset", group: "Film Editor",
    description: "Slide this shot's voice-over earlier or later against the picture, in seconds.",
    route: FILM, anchor: ANCHORS.quickVoOffset, label: "Film Editor → quick panel → vo offset",
    keywords: ["vo", "offset", "sync", "dialogue", "audio timing"],
    howTo: "Select a shot and edit vo offset in the quick panel." },
  { name: "mute_shot_vo", title: "Mute a shot's VO", group: "Film Editor",
    description: "Drop this shot's voice-over from the mix without deleting the take.",
    route: FILM, anchor: ANCHORS.quickMute, label: "Film Editor → quick panel → mute",
    keywords: ["mute", "vo", "silence", "drop audio"],
    howTo: "Tick mute in the selected shot's quick panel." },
  { name: "pick_what_plays", title: "Pick what plays", group: "Film Editor",
    description: "Choose which of a shot's takes is the one the cut uses, straight from the quick panel's strip.",
    route: FILM, anchor: ANCHORS.quickSource, label: "Film Editor → quick panel → what plays",
    keywords: ["plays", "source", "which take", "override", "choose"],
    howTo: "Select a shot and click a thumbnail in the \"what plays\" strip." },
  { name: "clear_source_override", title: "Clear the source override", group: "Film Editor",
    description: "Drop a shot's explicit pick so it falls back to its default (the keeper, or the newest motion).",
    route: FILM, anchor: ANCHORS.quickSource, label: "Film Editor → quick panel → what plays",
    keywords: ["clear", "default", "reset", "override", "fallback"],
    howTo: "In the \"what plays\" strip, click the currently highlighted take again to clear the override." },
  { name: "play_a_cut", title: "Play a cut", group: "Film Editor",
    description: "Watch a rendered animatic from the Cuts gallery without leaving the Film Editor.",
    route: FILM, anchor: ANCHORS.filmCutPlay, label: "Film Editor → Cuts gallery",
    keywords: ["play", "watch", "animatic", "cut", "gallery"],
    howTo: "Click an item in the Cuts gallery under the strip." },
  { name: "film_cue_strip", title: "The cue strip", group: "Film Editor",
    description: "Every music and SFX cue on the film, with its film time, level in dB and length.",
    route: FILM, anchor: ANCHORS.filmCues, label: "Film Editor → cue strip",
    keywords: ["cues", "music", "sfx", "score", "strip", "audio bed"],
    howTo: "Scroll to the cue strip under the Cuts gallery." },
  { name: "remove_film_cue", title: "Remove a cue", group: "Film Editor",
    description: "Take one music or SFX cue off the film's audio bed. The audio file stays as a take.",
    route: FILM, anchor: ANCHORS.filmCueRemove, label: "Film Editor → cue strip → remove",
    keywords: ["remove cue", "delete cue", "unplace", "music", "sfx"],
    howTo: "Press ✕ on a cue in the cue strip." },

  // ------------------------------------------------------------------ Shot Editor
  { name: "shot_compose_tab", title: "Compose tab", group: "Shot Editor",
    description: "The cel workbench: a background plus z-ordered animated layers, each rerollable on its own.",
    route: SHOT, query: { tab: "compose" }, anchor: shotTabAnchor("compose"),
    label: "Shot Editor → compose",
    keywords: ["compose", "comp", "cel", "layers", "tab"],
    howTo: "Press compose in the Shot Editor's tab row." },
  { name: "shot_generate_tab", title: "Generate tab", group: "Shot Editor",
    description: "Where new takes are made: stills, restyles, animated cels and chained beats.",
    route: SHOT, query: { tab: "generate" }, anchor: shotTabAnchor("generate"),
    label: "Shot Editor → generate",
    keywords: ["generate", "make", "new take", "tab"],
    howTo: "Press generate in the Shot Editor's tab row." },
  { name: "shot_motion_tab", title: "Motion edits tab", group: "Shot Editor",
    description: "The held-cel edits: freeze the tail of a clip, or trim it to its live first seconds.",
    route: SHOT, query: { tab: "motion" }, anchor: shotTabAnchor("motion"),
    label: "Shot Editor → motion edits",
    keywords: ["motion", "freeze", "trim", "edits", "tab"],
    howTo: "Press motion edits in the Shot Editor's tab row." },
  { name: "shot_audio_tab", title: "Audio tab", group: "Shot Editor",
    description: "Voice-over synthesis, VO timing, and the music and SFX console for this shot.",
    route: SHOT, query: { tab: "audio" }, anchor: shotTabAnchor("audio"),
    label: "Shot Editor → audio",
    keywords: ["audio", "vo", "voice", "music", "sfx", "tab"],
    howTo: "Press audio in the Shot Editor's tab row." },
  { name: "shot_script_tab", title: "Script tab", group: "Shot Editor",
    description: "The shot as written: image and motion prompts, dialogue, narration, sfx, cut notes and the curation note.",
    route: SHOT, query: { tab: "script" }, anchor: ANCHORS.scriptPanel,
    label: "Shot Editor → script",
    keywords: ["script", "prompt", "dialogue", "notes", "written", "tab"],
    howTo: "Press script in the Shot Editor's tab row." },
  { name: "hear_the_shot", title: "Hear the shot (monitor audio)", group: "Shot Editor",
    description: "Play the narration, the music bed and the SFX under the take in the monitor, mixed the way the cut will mix them.",
    route: SHOT, anchor: ANCHORS.monitorAudio, label: "Shot Editor → monitor → 🔊 audio",
    keywords: ["audio", "hear", "sound", "monitor", "mix", "vo", "music", "sfx", "bed", "listen", "silent"],
    howTo: "Press 🔊 audio under the monitor (it stays on between visits). A clip take plays its mix as the video runs; for a still, press ▶ play still to hold the frame for the shot's length with the same mix." },
  { name: "filter_takes", title: "Filter the takes rail", group: "Shot Editor",
    description: "Narrow the rail to stills, restyles, motion, fx or crops so a long shot stays readable.",
    route: SHOT, anchor: ANCHORS.takesFilter, label: "Shot Editor → takes filter",
    keywords: ["filter", "takes", "stills", "motion", "crops", "kind"],
    howTo: "Press one of the kind buttons above the takes rail." },
  { name: "compose_on_take", title: "Compose on a take", group: "Shot Editor",
    description: "Stage a new comp on any take — a still plate, or a clip for a moving background under the cels.",
    route: SHOT, anchor: ANCHORS.takeCompose, label: "Shot Editor → take → 🎬 compose on this",
    keywords: ["compose", "stage", "comp", "on this", "background"],
    howTo: "Select a take and press 🎬 compose on this under the monitor." },
  { name: "open_freeze_console", title: "Freeze console", group: "Shot Editor",
    description: "Jump from a clip in the rail to the motion tab with that clip loaded, ready to freeze or trim.",
    route: SHOT, anchor: ANCHORS.takeFreeze, label: "Shot Editor → take → ❄ freeze",
    keywords: ["freeze", "hold", "console", "motion edit"],
    howTo: "Select a motion take and press ❄ freeze… under the monitor." },
  { name: "gen_model_picker", title: "Backend and model picker", group: "Shot Editor",
    description: "Choose which backend and model a lane runs on for this submission, without changing the project default.",
    route: SHOT, query: { tab: "generate" }, anchor: ANCHORS.genModel,
    label: "Shot Editor → Generate → backend/model",
    keywords: ["backend", "model", "picker", "provider", "which model"],
    howTo: "Use the backend and model dropdowns at the top of any generate console." },
  { name: "gen_sub_still", title: "Generate → Still", group: "Shot Editor",
    description: "Make new plates for the shot from its image prompt.",
    route: SHOT, query: { tab: "generate", sub: "still" }, anchor: genSubAnchor("still"),
    label: "Shot Editor → Generate → Still",
    keywords: ["still", "plate", "image", "generate"],
    howTo: "Open the generate tab and press the still sub-tab." },
  { name: "gen_sub_restyle", title: "Generate → Restyle", group: "Shot Editor",
    description: "Push an existing take through img2img: keep the staging, change the look.",
    route: SHOT, query: { tab: "generate", sub: "restyle" }, anchor: genSubAnchor("restyle"),
    label: "Shot Editor → Generate → Restyle",
    keywords: ["restyle", "i2i", "img2img", "look", "variation"],
    howTo: "Open the generate tab and press the restyle sub-tab." },
  { name: "gen_sub_animate", title: "Generate → Animate", group: "Shot Editor",
    // One sentence only: what the model is likely to get wrong is situational,
    // so it rides on the generate/plan RESULTS, where it can be acted on.
    description: "Turn a still into motion — starts from the keeper unless \"animate from\" says otherwise; motion results carry situational guidance.",
    route: SHOT, query: { tab: "generate", sub: "animate" }, anchor: genSubAnchor("animate"),
    label: "Shot Editor → Generate → Animate",
    keywords: ["animate", "motion", "video", "i2v", "cel", "source", "keeper"],
    howTo: "Open the generate tab, press animate, and pick \"animate from\" (keeper or selected take)." },
  { name: "gen_sub_chain", title: "Generate → Chain", group: "Shot Editor",
    description: "String several motion beats into one continuous clip, each with its own live seconds and breath.",
    route: SHOT, query: { tab: "generate", sub: "chain" }, anchor: genSubAnchor("chain"),
    label: "Shot Editor → Generate → Chain",
    keywords: ["chain", "beats", "sequence", "stitch", "continuous"],
    howTo: "Open the generate tab and press the chain sub-tab." },
  { name: "still_prompt", title: "Still prompt", group: "Shot Editor",
    description: "The image prompt this still generates from. Empty means the shot's own written prompt.",
    route: SHOT, query: { tab: "generate", sub: "still" }, anchor: genFieldAnchor("still", "prompt"),
    label: "Shot Editor → Generate → Still → prompt",
    keywords: ["prompt", "still", "text", "describe"],
    howTo: "Type in the prompt box of the still console; leave it blank to use the script's prompt." },
  { name: "still_seeds", title: "Still seeds", group: "Shot Editor",
    description: "Fix the seeds so a still can be reproduced, or leave blank for fresh ones each time.",
    route: SHOT, query: { tab: "generate", sub: "still" }, anchor: genFieldAnchor("still", "seeds"),
    label: "Shot Editor → Generate → Still → seeds",
    keywords: ["seed", "seeds", "reproduce", "random", "deterministic"],
    howTo: "Enter comma-separated numbers in the seeds field of the still console." },
  { name: "generate_still", title: "Generate a still", group: "Shot Editor",
    description: "Submit the still console: one job per seed, each landing as a new take in the rail.",
    route: SHOT, query: { tab: "generate", sub: "still" }, anchor: genFieldAnchor("still", "submit"),
    label: "Shot Editor → Generate → Still → ▶",
    keywords: ["generate", "still", "submit", "run", "make plate"],
    howTo: "Press ▶ at the bottom of the still console." },
  { name: "restyle_prompt", title: "Restyle prompt", group: "Shot Editor",
    description: "What the restyle should become, applied to the take on the monitor.",
    route: SHOT, query: { tab: "generate", sub: "restyle" }, anchor: genFieldAnchor("restyle", "prompt"),
    label: "Shot Editor → Generate → Restyle → prompt",
    keywords: ["restyle", "prompt", "look", "grade", "change"],
    howTo: "Select a take, then type in the restyle console's prompt box." },
  { name: "restyle_denoise", title: "Restyle strength", group: "Shot Editor",
    description: "How far the restyle may travel from the source. Low keeps the drawing; high redraws it.",
    route: SHOT, query: { tab: "generate", sub: "restyle" }, anchor: genFieldAnchor("restyle", "denoise"),
    label: "Shot Editor → Generate → Restyle → denoise",
    keywords: ["denoise", "strength", "how much", "fidelity", "restyle"],
    howTo: "Drag the denoise slider in the restyle console before submitting." },
  { name: "generate_restyle", title: "Run a restyle", group: "Shot Editor",
    description: "Submit the restyle console against the selected take.",
    route: SHOT, query: { tab: "generate", sub: "restyle" }, anchor: genFieldAnchor("restyle", "submit"),
    label: "Shot Editor → Generate → Restyle → ▶",
    keywords: ["restyle", "submit", "run", "i2i"],
    howTo: "Press ▶ at the bottom of the restyle console." },
  { name: "animate_full_frame", title: "Full-frame animation", group: "Shot Editor",
    description: "Animate the whole plate instead of a region. Honest about the trade: the whole frame can boil.",
    route: SHOT, query: { tab: "generate", sub: "animate" }, anchor: genFieldAnchor("animate", "fullFrame"),
    label: "Shot Editor → Generate → Animate → full frame",
    keywords: ["full frame", "whole plate", "region", "boil", "animate"],
    howTo: "Tick full frame at the top of the animate console (untick it to draw a region instead)." },
  { name: "animate_region", title: "Animate a region", group: "Shot Editor",
    description: "Drag a box on the plate so only that part animates — the ink-first grammar that keeps the rest still.",
    route: SHOT, query: { tab: "generate", sub: "animate" }, anchor: genFieldAnchor("animate", "region"),
    label: "Shot Editor → Generate → Animate → region",
    keywords: ["region", "box", "crop", "only this", "ink first"],
    howTo: "With full frame unticked, drag a rectangle over the plate in the animate console." },
  { name: "animate_prompt", title: "Motion prompt", group: "Shot Editor",
    description: "Name only what moves. Everything you do not name is the background's job.",
    route: SHOT, query: { tab: "generate", sub: "animate" }, anchor: genFieldAnchor("animate", "prompt"),
    label: "Shot Editor → Generate → Animate → prompt",
    keywords: ["motion prompt", "what moves", "animate", "describe motion"],
    howTo: "Type in the animate console's prompt box; blank uses the shot's written motion prompt." },
  { name: "animate_frames", title: "Clip length in frames", group: "Shot Editor",
    description: "How many frames the model generates at 24fps. 49 is about two seconds and is the doctrine default.",
    route: SHOT, query: { tab: "generate", sub: "animate" }, anchor: genFieldAnchor("animate", "frames"),
    label: "Shot Editor → Generate → Animate → frames",
    keywords: ["frames", "length", "duration", "49", "97"],
    howTo: "Set the frames field in the animate console." },
  { name: "animate_sampler", title: "Steps and CFG", group: "Shot Editor",
    description: "The sampler dials: more steps is slower and cleaner, higher CFG follows the prompt harder.",
    route: SHOT, query: { tab: "generate", sub: "animate" }, anchor: genFieldAnchor("animate", "steps"),
    label: "Shot Editor → Generate → Animate → steps/cfg",
    keywords: ["steps", "cfg", "sampler", "quality", "guidance"],
    howTo: "Set steps and cfg in the animate console; leave them blank for the backend's defaults." },
  { name: "animate_freeze_after", title: "Freeze after", group: "Shot Editor",
    description: "Hold the pose after N live seconds so the clip stops moving instead of drifting. A true freeze, never a slow zoom.",
    route: SHOT, query: { tab: "generate", sub: "animate" }, anchor: genFieldAnchor("animate", "freeze_after"),
    label: "Shot Editor → Generate → Animate → freeze after",
    keywords: ["freeze", "hold", "first second law", "drift", "settle"],
    howTo: "Set freeze after (seconds) in the animate console; 1.0 is the house default." },
  { name: "generate_animate", title: "Run an animation", group: "Shot Editor",
    description: "Submit the animate console — the region or the full frame, at the frames and freeze you set.",
    route: SHOT, query: { tab: "generate", sub: "animate" }, anchor: genFieldAnchor("animate", "submit"),
    label: "Shot Editor → Generate → Animate → ▶",
    keywords: ["animate", "submit", "run", "motion", "generate clip"],
    howTo: "Press ▶ at the bottom of the animate console." },
  { name: "chain_beats", title: "Chain beats", group: "Shot Editor",
    description: "The JSON list of beats — each a prompt, its live seconds and the breath before the next one.",
    route: SHOT, query: { tab: "generate", sub: "chain" }, anchor: genFieldAnchor("chain", "beats"),
    label: "Shot Editor → Generate → Chain → beats",
    keywords: ["beats", "chain", "json", "sequence", "breath"],
    howTo: "Edit the beats JSON in the chain console: one object per movement, with prompt, live and breath." },
  { name: "generate_chain", title: "Run a chain", group: "Shot Editor",
    description: "Submit the chain console: each beat generates from the last one's final frame, stitched into one clip.",
    route: SHOT, query: { tab: "generate", sub: "chain" }, anchor: genFieldAnchor("chain", "submit"),
    label: "Shot Editor → Generate → Chain → ▶",
    keywords: ["chain", "submit", "run", "stitch", "beats"],
    howTo: "Press ▶ at the bottom of the chain console." },
  { name: "set_live_seconds", title: "Live seconds", group: "Shot Editor",
    description: "How much of a clip stays live before the freeze or the trim takes over.",
    route: SHOT, query: { tab: "motion" }, anchor: ANCHORS.motionLive,
    label: "Shot Editor → Motion edits → live",
    keywords: ["live", "seconds", "first second", "freeze point", "trim point"],
    howTo: "Set the live field in the motion edits tab before pressing ❄ or ✂." },
  { name: "vo_voice_picker", title: "Voice picker", group: "Shot Editor",
    description: "Which voice provider and voice this shot's line is synthesized with.",
    route: SHOT, query: { tab: "audio" }, anchor: ANCHORS.audioVoice,
    label: "Shot Editor → Audio → voice",
    keywords: ["voice", "vo", "elevenlabs", "speaker", "provider"],
    howTo: "Use the backend and voice dropdowns at the top of the audio tab." },
  { name: "vo_line", title: "The line", group: "Shot Editor",
    description: "The text that gets spoken. Blank uses the shot's narration or dialogue line from the script.",
    route: SHOT, query: { tab: "audio" }, anchor: ANCHORS.audioText,
    label: "Shot Editor → Audio → line",
    keywords: ["line", "text", "dialogue", "vo", "script"],
    howTo: "Type in the line box on the audio tab; v3 emotion tags pass straight through." },
  { name: "voice_treatment", title: "Voice treatment", group: "Shot Editor",
    description: "What the line is heard through: none, radio, phone, megaphone or a room. None is the default.",
    route: SHOT, query: { tab: "audio" }, anchor: ANCHORS.audioTreatment,
    label: "Shot Editor → Audio → treatment",
    keywords: ["treatment", "radio", "phone", "megaphone", "hall", "reverb", "broadcast", "telephone", "effect", "futz"],
    howTo: "Pick a treatment on the audio tab before synthesizing; none leaves the line clean." },
  { name: "music_prompt", title: "Music prompt", group: "Shot Editor",
    description: "Describe the cue you want written: instrumentation, tempo, feel.",
    route: SHOT, query: { tab: "audio" }, anchor: ANCHORS.musicPrompt,
    label: "Shot Editor → Audio → Music & SFX → music prompt",
    keywords: ["music", "prompt", "score", "cue", "bed"],
    howTo: "Type in the music prompt box of the Music & SFX section." },
  { name: "music_seconds", title: "Music length", group: "Shot Editor",
    description: "How many seconds of music to generate, 5 to 120.",
    route: SHOT, query: { tab: "audio" }, anchor: ANCHORS.musicSeconds,
    label: "Shot Editor → Audio → Music & SFX → seconds",
    keywords: ["seconds", "length", "music", "duration"],
    howTo: "Set the seconds field beside the music prompt." },
  { name: "music_instrumental", title: "Instrumental only", group: "Shot Editor",
    description: "Keep the cue wordless so it sits under dialogue instead of fighting it.",
    route: SHOT, query: { tab: "audio" }, anchor: ANCHORS.musicInstrumental,
    label: "Shot Editor → Audio → Music & SFX → instrumental",
    keywords: ["instrumental", "no vocals", "music", "under dialogue"],
    howTo: "Tick instrumental in the Music & SFX section." },
  { name: "sfx_prompt", title: "SFX prompt", group: "Shot Editor",
    description: "Describe one sound effect: \"a door latch clicking shut\", \"one cart wheel on cobbles\".",
    route: SHOT, query: { tab: "audio" }, anchor: ANCHORS.sfxPrompt,
    label: "Shot Editor → Audio → Music & SFX → sfx prompt",
    keywords: ["sfx", "sound effect", "foley", "prompt"],
    howTo: "Type in the sfx prompt box of the Music & SFX section." },
  { name: "sfx_seconds", title: "SFX length", group: "Shot Editor",
    description: "How long the effect runs, 1 to 10 seconds.",
    route: SHOT, query: { tab: "audio" }, anchor: ANCHORS.sfxSeconds,
    label: "Shot Editor → Audio → Music & SFX → seconds",
    keywords: ["sfx", "seconds", "length", "duration"],
    howTo: "Set the seconds field beside the sfx prompt." },
  { name: "shot_cue_list", title: "This shot's cues", group: "Shot Editor",
    description: "Every music and SFX cue anchored to this shot, with its offset and level.",
    route: SHOT, query: { tab: "audio" }, anchor: ANCHORS.shotCues,
    label: "Shot Editor → Audio → cues",
    keywords: ["cues", "music", "sfx", "anchored", "list"],
    howTo: "Scroll to the cue list at the bottom of the audio tab." },
  { name: "remove_shot_cue", title: "Remove a shot cue", group: "Shot Editor",
    description: "Take one cue off this shot. The generated audio stays as a take.",
    route: SHOT, query: { tab: "audio" }, anchor: ANCHORS.shotCueRemove,
    label: "Shot Editor → Audio → cues → remove",
    keywords: ["remove", "cue", "delete", "unplace"],
    howTo: "Press ✕ beside a cue in the audio tab's cue list." },
  { name: "pick_comp", title: "Switch comp", group: "Shot Editor",
    description: "A shot can hold several compositions; pick which one the workbench is showing.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.compPick,
    label: "Shot Editor → compose → comp picker",
    keywords: ["comp", "switch", "pick", "composition", "which"],
    howTo: "Press a comp's button at the top of the compose tab." },
  { name: "new_comp_from_plate", title: "New comp from the plate", group: "Shot Editor",
    description: "Stage a fresh composition on the shot's keeper plate, ready for cel layers.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.compCreate,
    label: "Shot Editor → compose → + new comp",
    keywords: ["new comp", "stage", "plate", "create composition"],
    howTo: "Press + new comp from plate at the top of the compose tab." },
  { name: "separate_figure", title: "Separate a figure", group: "Shot Editor",
    description: "Pull a character off the plate: SAM finds them from your clicks, the plate behind is painted clean, and you get a comp whose figure layer is ready to animate.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.compSeparate,
    label: "Shot Editor → compose → ✂ separate figure",
    keywords: ["separate", "figure", "cut out", "sam", "clean plate", "matte"],
    howTo: "Press ✂ separate figure in the compose tab, then click the character on the plate." },

  // ------------------------------------------------------------------ Cel workbench
  { name: "draw_cel_region", title: "Draw a cel region", group: "Cel workbench",
    description: "Drag a box on empty background to plan a new cel — the region is snapped to /32 so the model gets a legal size.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.compStage,
    label: "Cel workbench → stage",
    keywords: ["draw", "region", "box", "new cel", "stage"],
    howTo: "Drag on an empty part of the background in the compose tab's stage." },
  { name: "new_cel_prompt", title: "New cel prompt", group: "Cel workbench",
    description: "The motion prompt for the cel you just drew. Name only what moves inside that box.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.compNewPrompt,
    label: "Cel workbench → new cel → prompt",
    keywords: ["cel", "prompt", "motion", "new layer"],
    howTo: "After drawing a region, type in the motion prompt box that appears under the stage." },
  { name: "move_cel_layer", title: "Move a cel", group: "Cel workbench",
    description: "Drag an existing cel around the background; the composite re-renders about a second later.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.compStage,
    label: "Cel workbench → stage",
    keywords: ["move", "drag", "reposition", "cel", "layer"],
    howTo: "Drag inside a cel's rectangle on the stage." },
  { name: "resize_cel_layer", title: "Resize a cel", group: "Cel workbench",
    description: "Drag a corner handle to change a cel's region without regenerating it.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.compStage,
    label: "Cel workbench → stage",
    keywords: ["resize", "corner", "handle", "bigger", "smaller"],
    howTo: "Drag one of the corner handles of a cel on the stage." },
  { name: "nudge_cel_layer", title: "Nudge a cel", group: "Cel workbench",
    description: "Move the selected cel one pixel at a time with the arrow keys, ten with shift.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.compLayerSelect,
    label: "Cel workbench → keyboard",
    keywords: ["nudge", "arrows", "keyboard", "pixel", "shift"],
    howTo: "Click a cel to select it, then press the arrow keys (hold shift for ten pixels)." },
  { name: "select_cel_layer", title: "Select a layer", group: "Cel workbench",
    description: "Make one layer the target of the keyboard, the sliders and the reroll buttons.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.compLayerSelect,
    label: "Cel workbench → layer → id",
    keywords: ["select", "layer", "click", "target", "active"],
    howTo: "Click the layer's id on its card, or click its rectangle on the stage." },
  { name: "delete_cel_key", title: "Delete the selected cel", group: "Cel workbench",
    description: "Remove the selected layer with the delete key — the keyboard shortcut for the remove button.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.compLayerRemove,
    label: "Cel workbench → keyboard",
    keywords: ["delete", "backspace", "remove", "keyboard", "layer"],
    howTo: "Select a cel and press delete or backspace (not while typing in a field)." },
  { name: "undo_comp_edit", title: "Undo a comp edit", group: "Cel workbench",
    description: "Step back through the last twenty layer edits: moves, resizes, removals, opacity and z changes.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.compStage,
    label: "Cel workbench → keyboard",
    keywords: ["undo", "cmd z", "ctrl z", "back", "revert"],
    howTo: "Press ⌘Z (Ctrl+Z) with the compose tab focused and no field selected." },
  { name: "cel_matte_mode", title: "Matte mode", group: "Cel workbench",
    description: "window is a feathered rectangle; figure runs a per-frame anime matte so only the character lands on the background.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.compLayerMatte,
    label: "Cel workbench → layer → matte",
    keywords: ["matte", "window", "figure", "cutout", "feather"],
    howTo: "Choose window or figure in the dropdown on the layer's card." },
  { name: "cel_z_order", title: "Layer order", group: "Cel workbench",
    description: "Bring a cel forward or send it back so overlapping layers stack the way you want.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.compLayerZ,
    label: "Cel workbench → layer → z",
    keywords: ["z", "order", "front", "back", "stack", "forward"],
    howTo: "Press ▲ or ▼ on the layer's card." },
  { name: "cel_opacity", title: "Layer opacity", group: "Cel workbench",
    description: "How strongly a cel reads over the background — full strength, or a ghost.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.compLayerOpacity,
    label: "Cel workbench → layer → opacity",
    keywords: ["opacity", "alpha", "transparent", "ghost", "blend"],
    howTo: "Drag the small slider on the layer's card." },
  { name: "activate_cel_variant", title: "Use another cel take", group: "Cel workbench",
    description: "A layer keeps every cel it has ever generated; click one to make it the take the comp uses.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.compLayerVariant,
    label: "Cel workbench → layer → variants",
    keywords: ["variant", "take", "alternative", "compare", "switch cel"],
    howTo: "Click a thumbnail in the layer's stored-takes strip." },
  { name: "spotlight_cel", title: "Spotlight a cel", group: "Cel workbench",
    description: "Blow one cel up full-screen to judge it on its own before choosing.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.compLayerSpotlight,
    label: "Cel workbench → layer → spotlight",
    keywords: ["spotlight", "fullscreen", "enlarge", "inspect", "view"],
    howTo: "Click a layer's big thumbnail, or press ⛶ under one of its variants." },
  { name: "directed_reroll_console", title: "Directed reroll console", group: "Cel workbench",
    description: "Reroll one cel with a changed prompt, a fixed seed, or a different backend and model.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.compLayerDirected,
    label: "Cel workbench → layer → directed reroll",
    keywords: ["directed", "reroll", "seed", "prompt", "model", "console"],
    howTo: "Press 🎛 directed reroll… on the layer's card, adjust the fields, then press ▶ reroll." },
  { name: "activate_background", title: "Switch background", group: "Cel workbench",
    description: "Every background this comp has used stays stored; click one to put it back under the cels. Stills and clips both.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.compBgPlate,
    label: "Cel workbench → Background → stored",
    keywords: ["background", "plate", "switch", "history", "stored", "clip"],
    howTo: "Click a thumbnail in the stored-backgrounds strip in the Background section." },
  { name: "comp_duration", title: "Comp duration", group: "Cel workbench",
    description: "How long the rendered composite runs, in seconds. Layers hold their last frame past their own length.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.compDuration,
    label: "Cel workbench → duration",
    keywords: ["duration", "seconds", "length", "comp", "hold"],
    howTo: "Edit the duration field at the bottom of the compose tab (it commits when you leave the field)." },
  { name: "comp_auto_render", title: "Automatic re-render", group: "Cel workbench",
    description: "Layer edits persist immediately and the composite re-renders about a second and a half after the last change, so a drag does not spawn a job per pixel.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.compRender,
    label: "Cel workbench → render",
    keywords: ["auto", "re-render", "debounce", "preview", "automatic"],
    howTo: "Just edit — it re-renders on its own. Press ▶ render composite to force one now." },

  // ------------------------------------------------------------------ Separate a figure
  { name: "separate_points", title: "Click the figure", group: "Separate a figure",
    description: "Click the character to build a matte; the amber overlay shows what SAM has grabbed so far.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.sepCanvas,
    label: "Separate → canvas",
    keywords: ["click", "points", "sam", "figure", "matte", "select"],
    howTo: "Click on the character in the separate canvas; each click refines the matte." },
  { name: "separate_include_exclude", title: "Include or exclude", group: "Separate a figure",
    description: "Positive clicks add to the matte, negative clicks carve away what it grabbed by mistake.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.sepExclude,
    label: "Separate → ＋ / －",
    keywords: ["include", "exclude", "positive", "negative", "carve", "refine"],
    howTo: "Press － exclude and click the wrong area (or just shift-click anywhere)." },
  { name: "separate_undo", title: "Undo a point", group: "Separate a figure",
    description: "Drop the last click, or clear them all and start the matte again.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.sepUndo,
    label: "Separate → undo / clear",
    keywords: ["undo", "clear", "points", "start over", "reset"],
    howTo: "Press undo to drop the last point, or clear to remove them all." },
  { name: "separate_run", title: "Separate and clean the plate", group: "Separate a figure",
    description: "Cut the figure, paint the plate behind it, and stage a comp whose figure layer animates from the original plate — no ghost where the figure stood.",
    route: SHOT, query: { tab: "compose" }, anchor: ANCHORS.sepSubmit,
    label: "Separate → ✂ separate & clean plate",
    keywords: ["separate", "clean plate", "inpaint", "lama", "run", "cut out"],
    howTo: "Once the matte looks right, press ✂ separate & clean plate." },

  // ------------------------------------------------------------------ Timeline
  { name: "timeline_zoom", title: "Zoom the timeline", group: "Timeline",
    description: "Scale the lanes from a whole-film overview down to individual frames.",
    route: TIMELINE, anchor: ANCHORS.timelineZoom, label: "Timeline → zoom",
    keywords: ["zoom", "scale", "pixels per frame", "wider", "closer"],
    howTo: "Drag the zoom slider at the top right of the Timeline page." },
  { name: "timeline_scope", title: "Cut scope", group: "Timeline",
    description: "Cut the whole film, or just one act, without leaving the Timeline.",
    route: TIMELINE, anchor: ANCHORS.timelineScope, label: "Timeline → cut scope",
    keywords: ["scope", "act", "whole film", "partial", "cut range"],
    howTo: "Pick whole film or an act in the dropdown beside 🎞 cut the film." },
  { name: "timeline_play", title: "Play the preview", group: "Timeline",
    description: "Run the lifted FreeCut player over the compiled clip model — the same model the cut is assembled from.",
    route: TIMELINE, anchor: ANCHORS.timelinePlay, label: "Timeline → play",
    keywords: ["play", "pause", "preview", "watch", "player"],
    howTo: "Press ▶ under the preview window (⏸ stops it)." },
  { name: "timeline_mute", title: "Mute the preview", group: "Timeline",
    description: "Silence the preview's VO, music and SFX without stopping the picture.",
    route: TIMELINE, anchor: ANCHORS.timelineMute, label: "Timeline → 🔊 mute",
    keywords: ["mute", "silence", "sound", "audio", "volume", "quiet", "unmute"],
    howTo: "Press 🔊 beside the play button under the preview window." },
  { name: "timeline_step", title: "Step a frame", group: "Timeline",
    description: "Move the playhead one frame at a time to check an edit point exactly.",
    route: TIMELINE, anchor: ANCHORS.timelineStepFwd, label: "Timeline → step",
    keywords: ["step", "frame", "forward", "back", "nudge playhead"],
    howTo: "Press ◀ or ▶ beside the play button." },
  { name: "timeline_scrub", title: "Scrub the film", group: "Timeline",
    description: "Drag the playhead across the whole film to find a moment fast.",
    route: TIMELINE, anchor: ANCHORS.timelineScrub, label: "Timeline → scrub bar",
    keywords: ["scrub", "seek", "playhead", "drag", "find"],
    howTo: "Drag the long slider under the preview window." },
  { name: "timeline_ruler_seek", title: "Seek from the ruler", group: "Timeline",
    description: "Click the time ruler above the lanes to jump the playhead there.",
    route: TIMELINE, anchor: ANCHORS.timelineRuler, label: "Timeline → ruler",
    keywords: ["ruler", "seek", "click", "time", "jump"],
    howTo: "Click anywhere on the time ruler above the tracks." },
  { name: "timeline_move_audio", title: "Drag audio in time", group: "Timeline",
    description: "Slide a VO line or a music/SFX cue along its lane to lift it off a clip it overlaps.",
    route: TIMELINE, anchor: ANCHORS.timelineAudioDrag, label: "Timeline → A1 / MUSIC / SFX lane",
    keywords: ["drag", "move", "slide", "audio", "vo", "cue", "sfx", "music", "overlap", "retime"],
    howTo: "Drag the clip along its lane — it snaps to cuts and the playhead, shows the new time, and Esc cancels the drag." },
  { name: "timeline_select_clip", title: "Inspect a clip", group: "Timeline",
    description: "Click a clip to see its frame range, its source in/out, its media handles and its Genga Studio lineage.",
    route: TIMELINE, anchor: ANCHORS.timelineClip, label: "Timeline → clip",
    keywords: ["clip", "select", "inspect", "handles", "lineage", "source"],
    howTo: "Click a clip block in one of the lanes; its detail card appears below." },
  { name: "timeline_cut", title: "Cut the film from the Timeline", group: "Timeline",
    description: "Assemble the film as it stands into a watchable cut, with the job's progress beside the button.",
    route: TIMELINE, anchor: ANCHORS.timelineRender, label: "Timeline → 🎞 cut the film",
    keywords: ["cut", "assemble", "animatic", "render", "watch"],
    howTo: "Press 🎞 cut the film at the top of the Timeline page; the status beside it turns into “cut ready · open”." },

  // ------------------------------------------------------------------ Jobs
  { name: "select_job", title: "Inspect a job", group: "Jobs",
    description: "Click a job to see its type, worker, error and result payload.",
    route: JOBS, anchor: ANCHORS.jobsRow, label: "Jobs → row",
    keywords: ["job", "select", "inspect", "detail", "result"],
    howTo: "Click a row in the jobs table." },
  { name: "cancel_job", title: "Cancel a job", group: "Jobs",
    description: "Stop a queued or running job before it costs any more time or money.",
    route: JOBS, anchor: ANCHORS.jobsCancel, label: "Jobs → cancel",
    keywords: ["cancel", "stop", "kill", "abort", "queue"],
    howTo: "Press ✕ at the right of a queued or running job's row." },
  { name: "job_live_log", title: "Live job log", group: "Jobs",
    description: "Follow a running job's output as it streams, or read the tail of a finished one.",
    route: JOBS, anchor: ANCHORS.jobsLog, label: "Jobs → log",
    keywords: ["log", "live", "stream", "output", "debug", "tail"],
    howTo: "Select a job — its log streams in the right-hand pane." },

  // ------------------------------------------------------------------ Settings
  { name: "enable_backend", title: "Enable or disable a backend", group: "Settings",
    description: "Turn a backend on or off for every lane it serves, without deleting its configuration.",
    route: SETTINGS, anchor: ANCHORS.settingsBackendEnable, label: "Settings → backend → enable",
    keywords: ["enable", "disable", "backend", "on", "off", "toggle"],
    howTo: "Press enable or disable on the backend's card in Settings." },
  { name: "check_backend_health", title: "Check a backend's health", group: "Settings",
    description: "Probe a backend right now and see what it says — the fastest way to find a dead key or an offline GPU box.",
    route: SETTINGS, anchor: ANCHORS.settingsBackendHealth, label: "Settings → backend → health",
    keywords: ["health", "probe", "up", "down", "check", "connection"],
    howTo: "Press health on the backend's card; the answer appears under it." },
  { name: "edit_backend", title: "Edit a backend", group: "Settings",
    description: "Open a backend's fields: its label, its base url and its stored API key.",
    route: SETTINGS, anchor: ANCHORS.settingsBackendEdit, label: "Settings → backend → ⚙",
    keywords: ["edit", "settings", "configure", "backend", "gear"],
    howTo: "Press ⚙ on the backend's card." },
  { name: "backend_api_key", title: "Backend API key", group: "Settings",
    description: "Store a provider key on the server. Leaving the field blank keeps the key already stored.",
    route: SETTINGS, anchor: ANCHORS.settingsBackendKey, label: "Settings → backend → api key",
    keywords: ["key", "api key", "token", "secret", "credential"],
    howTo: "Open a backend with ⚙, type the key in the api key field, and press save." },
  { name: "backend_options_json", title: "Backend options JSON", group: "Settings",
    description: "The per-backend options blob: lane overrides, model names, concurrency, cost per job and remote settings.",
    route: SETTINGS, anchor: ANCHORS.settingsBackendOptions, label: "Settings → backend → options",
    keywords: ["options", "json", "advanced", "concurrency", "cost", "override"],
    howTo: "Open a backend with ⚙ and edit the options JSON textarea, then press save." },
  { name: "save_backend", title: "Save a backend", group: "Settings",
    description: "Write the edited label, url, key and options back to the server.",
    route: SETTINGS, anchor: ANCHORS.settingsBackendSave, label: "Settings → backend → save",
    keywords: ["save", "apply", "backend", "write", "commit"],
    howTo: "Press save under the backend's edit fields." },
  { name: "delete_backend", title: "Delete a backend", group: "Settings",
    description: "Remove a backend entirely. Jobs already recorded keep their reference to it.",
    route: SETTINGS, anchor: ANCHORS.settingsBackendDelete, label: "Settings → backend → delete",
    keywords: ["delete", "remove", "backend", "drop"],
    howTo: "Open a backend with ⚙ and press delete." },
  { name: "add_backend", title: "Add a backend", group: "Settings",
    description: "Register another generator: a ComfyUI box on your network, or a hosted API with your own key.",
    route: SETTINGS, anchor: ANCHORS.settingsAdd, label: "Settings → + add backend",
    keywords: ["add", "new backend", "comfyui", "provider", "register"],
    howTo: "Press + add backend in Settings, fill id, type, base url and key, then press add." },
  { name: "lane_defaults_table", title: "Lane defaults", group: "Settings",
    description: "Which backend and model each lane uses when a generate console is left blank — what the pickers call \"(project default)\".",
    route: SETTINGS, anchor: ANCHORS.settingsLane, label: "Settings → Where each part of the film is made",
    keywords: ["lane", "default", "project default", "routing", "which model"],
    howTo: "Scroll to \"Where each part of the film is made\" in Settings and pick a backend for the lane." },
  { name: "api_token", title: "Access link", group: "Settings",
    description: "The studio is invite-only. An access link stores your token in this browser; a token can also be pasted in by hand. It is never stored on the server.",
    route: SETTINGS, anchor: ANCHORS.settingsToken, label: "Settings → Access link",
    keywords: ["token", "access", "link", "invite", "auth", "login", "password"],
    howTo: "Paste the token under Access link in Settings and press save." },

  // ------------------------------------------------------------------ Director chat
  { name: "chat_provider", title: "Chat provider", group: "Director chat",
    description: "Which LLM answers in the director chat, or auto to use the first enabled direction backend.",
    route: CHAT, anchor: ANCHORS.chatProvider, label: "Director chat → provider",
    keywords: ["provider", "llm", "claude", "model", "chat"],
    howTo: "Pick a provider in the dropdown at the top right of the chat." },
  { name: "chat_send", title: "Direct the film in chat", group: "Director chat",
    description: "Say what you want in plain language. Simple edits compile through the deterministic grammar; richer direction goes to your configured LLM, which can inspect the film and run plans.",
    route: CHAT, anchor: ANCHORS.chatInput, label: "Director chat → message",
    keywords: ["chat", "send", "direct", "ask", "instruction", "talk"],
    howTo: "Type in the box at the bottom of the chat and press enter (shift-enter for a new line)." },
];

/** Every palette-only feature, in page order. */
export const FEATURES: ActionDef[] = SPECS.map(feature);

export const FEATURES_BY_NAME: Record<string, ActionDef> =
  Object.fromEntries(FEATURES.map((f) => [f.name, f]));

/** Page name → how many features live there (list_features' `groups`). */
export function featureGroups(defs: ActionDef[] = FEATURES): Record<string, number> {
  const out: Record<string, number> = {};
  for (const d of defs) out[d.group || "Other"] = (out[d.group || "Other"] || 0) + 1;
  return out;
}
